<?php

/**
 * @file
 * Hooks and functions related to access_by_field.module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function access_by_field_help($route_name, $route_match) {
  switch ($route_name) {
    case 'help.page.access_by_field':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module allows the additional access restrictions based on a value of a common field between user and entity.') . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Content Mapping Configuration') . '</dt>';
      $output .= '<dd>' . t('This page lists down content types with a configure link that takes to the fields mapping form page.') . '</dd>';
      $output .= '<dt>' . t('Fields Mappings') . '</dt>';
      $output .= '<dd>' . t('This form takes care of mapping between Entity & User fields.') . '</dd>';
      $output .= '<dt>' . t('Bypass Roles') . '</dt>';
      $output .= '<dd>' . t('If a role needs unrestricted access to the entity, it can be bypassed from this form.') . '</dd>';
      $output .= '<dt>' . t('Mapping Dashboard') . '</dt>';
      $output .= '<dd>' . t('A lit of all mappings done in Mapping Form can be found here.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_node_access().
 */
function access_by_field_node_access(NodeInterface $node, $op, AccountInterface $account) {
  // Define the field name for which mapping will be done.
  $mapping_config = \Drupal::config('abf_fields_mapping.settings');
  $field_name = $mapping_config->get('user_fields');

  $user = \Drupal::entityTypeManager()->getStorage('user') ::load($account->id());
  $roles = $account->getRoles(TRUE);

  // Get bypassed roles and skip the access mapping for those roles.
  $bypassed_roles = \Drupal::config('abf_bypass_roles.settings')
    ->get('bypassed_roles');
  if (empty($bypassed_roles)) {
    // Default bypass checks for administrator role.
    $bypassed_roles['administrator'] = 'administrator';
  }

  foreach (array_filter($bypassed_roles, 'ucfirst') as $rid => $role) {
    if (in_array($rid, $roles)) {
      return;
    }
  }

  // Get node bundle.
  $type = $node->bundle();

  //check if node has field access tag.
  if ($node->hasField($field_name)) {
    // Get tag terms node is tagged with.
    $node_access = $node->$field_name->getValue();
  }
  else {
    return;
  }

  // Get user tag terms.
  $user_access = $user->$field_name->getValue();
  if (empty($user_access)) {
    // If user didn't have any access tags, skip.
    return;
  }
  switch ($op) {
    case 'view':
    case 'view all revisions':
      $node_access = array_column($node_access, 'target_id');
      $user_access = array_column($user_access, 'target_id');
      //Check if user is assigned to anyone of the access tag node has
      $access = array_intersect($user_access, $node_access);
      if (!empty($access)) {
        return AccessResult::allowed();
      }
      return AccessResult::forbidden();

    case 'update':
      // Check user has permission for edit node type and user and node both
      // have tag terms.
      if (($account
            ->hasPermission('edit any ' . $type . ' content') || $account
            ->hasPermission('edit own ' . $type . ' content') && $account
            ->id() == $node->getOwnerId()) &&
        !empty($node_access) &&
        !empty($user_access)
      ) {
        $node_access = array_column($node_access, 'target_id');
        $user_access = array_column($user_access, 'target_id');

        // Check if user is assigned to anyone of the access tag node has.
        $access = array_intersect($user_access, $node_access);
        if (is_array($access) && !empty($access)) {
          return AccessResult::allowed();
        }
      }
      return AccessResult::forbidden();

    case 'delete':
      $allowed = FALSE;
      // Check user has permission for delete node type and user and node
      // both have tag terms.
      if (($account
            ->hasPermission('delete any ' . $type . ' content') || $account
            ->hasPermission('delete own ' . $type . ' content') && $account
            ->id() == $node->getOwnerId()) &&
        !empty($node_access) &&
        !empty($user_access)
      ) {
        $node_access = array_column($node_access, 'target_id');
        $user_access = array_column($user_access, 'target_id');
        // Check if user is assigned to anyone of the access tags node has.
        $access = array_intersect($user_access, $node_access);
        if (is_array($access) && !empty($access)) {
          return AccessResult::allowed();
        }
      }
      return AccessResult::forbidden();
  }
}
